jittering:
  apply: true
  parameters:
    sigma: 1
  probability: 0.75
scaling:
  apply: true
  parameters:
    sigma: 1
  probability: 0.75
rotation:
  apply: false
  parameters: {}
  probability: 0.75
permutation:
  apply: true
  parameters:
    max_segments: 3
  probability: 0.75
channel_shuffle:
  apply: true
  parameters: {}
  probability: 0.75