experiment:
  seed: 28
  num_epochs_ssl: 300
  num_epochs_fine_tuning: 100
  batch_size_fine_tuning: 64

modalities:
  skeleton:
    model:
      cooccurrence:
        class_name: SupervisedSkeletonCooccurenceModel
        from_module: skeleton_coocurrence
        encoder_class_name: SkeletonCooccurenceBlocks
        encoder_name: blocks
        args: [] # These will be passed as positional args to the LightningModule class.
        kwargs: # These will be passed as kwargs to the LightningModule class.
          out_channels: [64, 32, 32, 64, 128, 256]
          kernel_sizes: [[1, 1], [3, 1], [3, 3], [3, 3], [3, 3], [3, 3]]
          max_pool_sizes: [null, null, 2, 2, 2, 2]
          sample_length: 50
          lr: 0.001
          optimizer_name: adam
      ssl:
        args: []
        kwargs:
          batch_size: 128
          sample_length: 50
          optimizer_name_ssl: "adam"
          lr: 0.001
          # SimCLR specific
          hidden:      [256, 128]
          temperature: 0.2
    transforms:
      - class_name: SkeletonSampler
        from_module: skeleton_transforms
        transform_name: sampling
        in_test: true
        kwargs:
          size: 50
      - class_name: ToTensor
        from_module: general_transforms
        in_test: true
      - class_name: Permute
        from_module: general_transforms
        in_test: true
        kwargs:
          shape: [1, 2, 0]
      - class_name: ToFloat
        from_module: general_transforms
        in_test: true